
export enum NameEvent{
    ON_SPIN = 'onSpin',
    REQUEST_SPIN = 'REQUEST_SPIN',
    REQUEST_STOP = 'REQUEST_STOP',
    REEL_STOPPED = 'REEL_STOPPED',
    CHECK_PRIZES = 'CHECK_PRIZES',
    PRIZES_FOUND = 'PRIZES_FOUND',
    PRIZES_PAY =  'SHOW_PAY_LABEl',
    GET_BET = 'GET_BET'
}
